/* Licensed under Apache-2.0 */

#ifndef CRYPTO_MARKETS_H_
#define CRYPTO_MARKETS_H_

/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Market type.
 */
typedef enum MarketType {
    Unknown,
    Spot,
    LinearFuture,
    InverseFuture,
    LinearSwap,
    InverseSwap,
    AmericanOption,
    EuropeanOption,
    QuantoFuture,
    QuantoSwap,
    Move,
    BVOL,
} MarketType;

/**
 * Fetch trading markets of a cryptocurrency exchange.
 */
const char *fetch_markets(const char *exchange, enum MarketType market_type);

/**
 * Deallocate a string.
 */
void deallocate_string(const char *pointer);

#endif /* CRYPTO_MARKETS_H_ */
