/* Licensed under Apache-2.0 */

#ifndef CRYPTO_MARKETS_FFI_H_
#define CRYPTO_MARKETS_FFI_H_

/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "crypto_market_type.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Fetch trading markets of a cryptocurrency exchange.
 */
const char *fetch_markets(const char *exchange, MarketType market_type);

/**
 * Deallocate a string.
 */
void deallocate_string(const char *pointer);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* CRYPTO_MARKETS_FFI_H_ */
